
import basmati_rice from '../../public/assets/basmati-rice.jpg'
import non_basmati from '../../public/assets/non-basmati.jpg'
import corn_maize from '../../public/assets/corn-maize.jpeg'
import sugar_cereal from '../../public/assets/sugar-cereal.jpg'
import fox_nuts from '../../public/assets/fox-nuts.jpg'
import pea_nuts from '../../public/assets/pea-nuts.jpg'
import lakdong_turmeric from '../../public/assets/turmeric-powder.webp'
import cardamom_spice from '../../public/assets/cardamom-spice.jpg'
import clove_spice from '../../public/assets/clove-spice.jpeg'
import cumin_masala from '../../public/assets/cumin-masala.jpeg'
import fenugreek_spice from '../../public/assets/fenugreek-spice.webp'
import red_chilli from '../../public/assets/red-chilli.jpg'
import fennel_seeds from '../../public/assets/fennel-seed.jpg'
import coriander_spice from '../../public/assets/coriander-spice.jpg'
import black_pepper from '../../public/assets/black-pepper.jpg'
import white_pepper from '../../public/assets/pepper-white.jpg'
import bay_powder from '../../public/assets/bay-powder.jpeg'
import grapes_fruit from '../../public/assets/grapes-fruit.webp'
import pome_fruit from '../../public/assets/pome-fruit.jpg'
import mango_fruit from '../../public/assets/mango-fruit.jpg'
import banana_fruit from '../../public/assets/banana-fruit.jpg'
import potato_veg from '../../public/assets/potato.jpg'
import onion_veg from '../../public/assets/onion-veg.jpg'
import garlic_veg from '../../public/assets/garlic-veg.jpg'
import ginger_veg from '../../public/assets/ginger-veg.webp'
import makhana_veg from '../../public/assets/makhana.jpeg'


const product_data = [
   {
      id:26,
      title: "Makhana Phool",
      description: "Fox nuts, or makhana phool (HS Code : 20081921 -Makhana powder/flour ), are nutritious, popped seeds from the prickly waterlily (Euryale ferox), a water plant...",
      image: makhana_veg,
      date: Date.now(),
      category: 'Edible seeds/ Nuts/ Dried fruits',
      heading1:"Makhana Phool or Fox Nut (HS Code : 20081921) -Makhana powder/flour : An Overview",
      para1a:"What is Fox Nuts (Makhana Phool)?",
      para1b:"Fox nuts, or makhana phool, are nutritious, popped seeds from the prickly waterlily (Euryale ferox), a water plant, not a true nut, popular in Asian cuisine as a healthy, a-low-calorie, b- gluten-free, c- snack rich in protein, fiber, and minerals",
      heading2:"Used:",
      para2a:"Roasted,in savory dishes, or sweets, especially during fasts and festivals (Diwali  and in the of Ramadan) in India",
      para2b:"They're known for their crunchy texture and health benefits, supporting heart, bone, and digestive health, and are a growing global superfood.",
      heading3:"What they are :",
      para3a:" 1.Origin: Seeds of the Euryale ferox plant, a type of water lily, harvested from Asian wetlands",
      para3b:"2. Process: The seeds are dried, heated, and popped, similar to popcorn, creating light, puffy kernels.",
      heading4:"Nutritional Highlights:",
      para4a:"1. Low in calories, fat, and sodium.",
      para4b:"2. Rich in protein, fiber, magnesium, potassium, phosphorus, and calcium. Contains antioxidants like kaempferol, helping fight inflammation.",
      heading5:"Nutritional Highlights (per 100g, approximate)",
      para5a:"a. Calories: Around 350",
      para5b:"b. Protein: ~9.7%",
      para5c:"c. Fiber: ~7.6%",
      para5d:"d. Carbohydrates: ~76g ",
      para5e:"e. Minerals: Good source of Calcium, Potassium, Phosphorus, Iron.",
      heading6:"Uses",
      para6a:"1. Snacking: Eaten plain, roasted with ghee and spices (masala), or flavored (caramel, peri-peri).",
      para6b:"2. Cooking: Added to curries, kheer (rice pudding), and halwa.",
      para6c:"3. Fasting: A popular, wholesome food during religious fasts (like Navratri Diwali and in the month of Ramadan) in India.",
      heading7:"Health Benefits",
      para7a:"a. Supports heart health",
      para7b:"b. Weight management and weight loss (High fiber and protein)",
      para7c:"c. Digestion, and Blood Sugar  Control  ( low GI)",
      para7d:"d. Strengthening bones ",
      para7e:"e. Digestive Health: Fiber promotes regularity and gut health, preventing constipation",
      para7f:"f. Antioxidant Power: Contain antioxidants like kaempferol and quercetin, fighting inflammation and protecting cells",
      para7g:"g. Skin Health: Antioxidants and amino acids help reduce signs of aging and promote glowing skin",
      para7h:"h. Sleep Aid: Contain tryptophan, an amino acid that promotes relaxation and better sleep quality.",
      para7i:"i. Kidney Health: Diuretic properties and antioxidants support kidney function and help prevent stone formation",
      para7j:"j. Pregnancy & Energy: Good source of iron, protein, and calcium, beneficial for energy and fetal development",
     },
   {
    id:1,
    title: "Basmati Rice",
    description: "Basmati rice, often hailed as the 'King of Rice,' is a long-grain variety known for its distinct aroma, slender grains, and soft, fluffy...",
    image: basmati_rice,
    date: Date.now(),
    category: 'Cereals',
    heading1: 'Basmati Rice: An Overview',
    para1a: "Basmati rice, often hailed as the 'King of Rice,' is a long-grain variety known for its distinct aroma, slender grains, and soft, fluffy texture when cooked. Originating from the Indian subcontinent, this rice has been cultivated for centuries in the fertile plains of the Himalayas, particularly in northern India and Pakistan. The word 'Basmati' is derived from Sanskrit, meaning 'fragrant,' which perfectly encapsulates its signature aroma that sets it apart from other rice varieties. Basmati is available in both white and brown varieties, each with unique characteristics and uses. White Basmati is polished, removing the bran and leaving behind a lighter texture, while brown Basmati retains its outer bran layer, offering a nuttier flavor and chewier consistency.",
    para1b: "Renowned not just for its taste and fragrance, Basmati rice has a long history of cultural significance, especially in Indian and Middle Eastern cuisine. Its use in dishes like biryani, pulao, and various curries reflects its versatility and ability to absorb flavors while maintaining its delicate texture. The grain elongates when cooked, becoming even longer without breaking, which makes it a preferred choice for special occasions and festive meals. Furthermore, Basmati rice is considered a premium product, with strict geographical indications (GI) in place to protect its authenticity and ensure that it is sourced from the designated regions in India and Pakistan.",
    heading2:"Benefits of Basmati Rice",
    para2a:"The health benefits of Basmati rice are another reason for its growing popularity across the globe. One of its standout benefits is that it has a relatively low glycemic index (GI), especially in comparison to other types of white rice. This means that it releases energy more slowly into the bloodstream, leading to better blood sugar control, which is particularly beneficial for individuals managing diabetes. The low GI also makes it a good option for those looking to maintain a steady energy level and avoid spikes in blood sugar after meals.",
    para2b:"Additionally, Basmati rice is gluten-free, making it a suitable grain for individuals with celiac disease or gluten intolerance. It's also a good source of essential nutrients such as B vitamins, particularly thiamine and niacin, which play a crucial role in energy metabolism and maintaining healthy nerve function. Brown Basmati rice, in particular, offers added health benefits due to its higher fiber content. The fiber in brown Basmati helps promote better digestion, aids in weight management by creating a sense of fullness, and may reduce the risk of heart disease by lowering cholesterol levels. Furthermore, Basmati rice is low in fat and sodium, making it a heart-friendly food choice.",
    heading3:"Nutritional Value of Basmati Rice",
    para3a:"Basmati rice is not only favored for its flavor but also for its impressive nutritional profile. A typical serving (about 1 cup cooked) of white Basmati rice provides approximately 210 calories, with the majority coming from carbohydrates, which serve as a quick energy source. It contains about 45 grams of carbohydrates, 5 grams of protein, and very minimal fat, less than 1 gram. This makes it an excellent option for athletes or individuals with high energy needs. Although it has a lower fiber content compared to whole grains, white Basmati still provides small amounts of iron and magnesium, which are essential for maintaining oxygen circulation in the body and supporting muscle function.",
    para3b:"Moreover, the complex carbohydrates in Basmati rice provide sustained energy without the quick crash associated with simpler carbohydrate sources. Whether used as a base for savory dishes or enjoyed on its own, Basmati rice is a nutritionally dense grain that complements a well-balanced diet, providing both taste and health benefits."
   },
   {
    id:2,
    title: "Non-Basmati Rice",
    description: "Non-Basmati rice refers to a diverse category of rice varieties that do not fall under the  These rice types can be...",
    image: non_basmati,
    date: Date.now(),
    category: 'Cereals',
    heading1: 'Non-Basmati Rice: An Overview',
    para1a: "Non-Basmati rice refers to a diverse category of rice varieties that do not fall under the classification of Basmati rice. Unlike Basmati, which is known for its long grains, aromatic fragrance, and delicate texture, non-Basmati rice comes in various grain sizes, textures, and flavors. These rice types can be short, medium, or long-grain, and are cultivated in various regions across the world, particularly in Asia, Africa, and the Americas. Some of the common non-Basmati varieties include Sona Masoori, Ponni, Jasmine, Arborio, and Parboiled rice. Each type of non-Basmati rice has distinct characteristics, making them suitable for a wide range of dishes, from everyday meals to specialized recipes.",
    para1b: "Non-Basmati rice is a staple food in many parts of the world, often forming the foundation of daily meals. In India, for instance, Sona Masoori and Ponni are widely used in South Indian cuisine for dishes like idli, dosa, and steamed rice, while Jasmine rice is popular in Southeast Asian countries like Thailand and Vietnam. The versatility of non-Basmati rice makes it suitable for diverse culinary applications, whether you’re preparing risottos, sushi, stir-fries, or traditional rice porridges. Moreover, non-Basmati rice tends to be more affordable than Basmati, making it accessible to a broader population, particularly in regions where rice is a primary source of sustenance.",
    heading2:"Benefits of Non-Basmati Rice",
    para2a:"Non-Basmati rice varieties offer a range of health benefits depending on the type of rice and how it is processed. One of the primary benefits is that many non-Basmati rice types are rich in carbohydrates, providing a substantial source of energy, particularly for populations that rely on rice as a dietary staple. For example, Sona Masoori and Ponni rice are lighter and have a lower glycemic index (GI) than traditional white rice, making them suitable for people looking to maintain stable blood sugar levels. Parboiled rice, another popular non-Basmati variety, is partially boiled in the husk, which helps retain essential nutrients like vitamins and minerals, making it more nutrient-dense compared to regular white rice.",
    para2b:"Non-Basmati rice varieties are also gluten-free, making them ideal for people with celiac disease or gluten intolerance. The wide availability of whole grain and brown non-Basmati rice options allows consumers to choose more fiber-rich alternatives, which can aid in digestion, promote satiety, and help manage weight. Additionally, rice like Jasmine or Arborio, despite being refined, still contains small amounts of essential nutrients such as B vitamins, iron, and magnesium, which contribute to better overall health. For those looking to include more plant-based proteins in their diets, certain types of non-Basmati rice, when combined with legumes, can form a complete protein source, particularly beneficial in vegetarian or vegan meal plans.",
    heading3:"Nutritional Value of Non-Basmati Rice",
    para3a:"The nutritional profile of non-Basmati rice varies significantly depending on the variety and whether it is polished or unpolished. A typical serving of white non-Basmati rice, such as Sona Masoori, provides around 200 calories per cup, primarily from carbohydrates (around 45 grams), which serve as an excellent source of energy. The protein content is moderate, around 4-5 grams per serving, and the fat content is negligible, making it a low-fat food. Non-Basmati rice is also naturally low in sodium and cholesterol, which makes it heart-friendly when prepared without added fats or salt.",
    para3b:"Additionally, unpolished non-Basmati rice varieties tend to retain more vitamins like niacin, thiamine, and folate, which are crucial for energy production and the maintenance of a healthy nervous system. In general, non-Basmati rice, regardless of its form, provides a versatile and nutritious option for a balanced diet, offering both culinary diversity and essential nutrients for overall well-being."
   },
   {
    id:3,
    title: "Maize",
    description: "Maize, commonly known as corn, is one of the world’s most widely cultivated crops, originating in Mexico over 10,000 years ago...",
    image: corn_maize,
    date: Date.now(),
    category: 'Cereals',
    heading1:"Maize: An Overview",
    para1a:"Maize, commonly known as corn, is one of the world’s most widely cultivated crops, originating in Mexico over 10,000 years ago. Today, it is a dietary staple in many regions, especially in North and South America, Africa, and parts of Asia. Maize is incredibly versatile, with varieties such as sweet corn, field corn, and popcorn used in a wide range of applications, from fresh consumption to processed foods like cornmeal, tortillas, and breakfast cereals. Beyond its role in the food industry, maize is also essential in livestock feed and biofuel production, underscoring its global economic importance.",
    para1b:"Maize’s adaptability to various climates and soils has made it a reliable crop for food security. It thrives in diverse regions, and its significance spans cultural, economic, and culinary boundaries. From staple dishes in African countries like ugali and pap to tortillas in Latin America and cornbread in the southern United States, maize plays a central role in traditional diets worldwide. Whether eaten fresh, dried, or processed, maize is a fundamental crop that sustains millions of people across the globe.",
    heading2:"Benefits of Maize",
    para2a:"Maize provides numerous health benefits, making it a valuable part of a balanced diet. It is rich in carbohydrates, offering a steady source of energy, especially for people with high physical demands. Whole grain maize, like cornmeal or popcorn, is high in dietary fiber, which supports digestive health by promoting regular bowel movements and preventing constipation. Fiber also aids in managing weight by enhancing feelings of fullness and can contribute to lowering cholesterol levels, thereby supporting heart health.",
    para2b:"Maize is naturally gluten-free, making it a suitable option for individuals with celiac disease or gluten intolerance. It is also packed with essential vitamins and minerals, including B vitamins like thiamine, niacin, and folate, which are crucial for energy metabolism and nervous system health. Sweet corn is particularly rich in antioxidants like lutein and zeaxanthin, which promote eye health by protecting against macular degeneration and cataracts.",
    heading3:"Nutritional Value of Maize",
    para3a:"Maize offers a solid nutritional profile. A typical serving of cooked maize (about 1 cup) contains around 177 calories, mostly from its 41 grams of carbohydrates. It also provides about 5 grams of protein and 2 grams of fat. Whole grain maize products, such as cornmeal and popcorn, offer higher fiber content, typically around 3-4 grams per serving, which supports digestive health and helps regulate blood sugar levels.",
    para3b:"Maize is also a good source of vitamin C, providing approximately 17% of the daily recommended intake, which boosts immune function and skin health. Additionally, it is rich in essential minerals like magnesium, potassium, and phosphorus, which contribute to muscle function, bone health, and proper fluid balance. These nutrients, combined with maize’s versatility, make it a nutritious and integral part of diets around the world.",
   },
   {
    id:4,
    title: "Sugar",
    description: "Sugar, a simple carbohydrate, is one of the most commonly consumed substances globally. It is naturally found in many foods, including...",
    image: sugar_cereal,
    date: Date.now(),
    category: 'Cereals',
    heading1:"Sugar: An Overview",
    para1a:"Sugar, a simple carbohydrate, is one of the most commonly consumed substances globally. It is naturally found in many foods, including fruits, vegetables, and dairy products, but most of the sugar in our diets comes from processed or refined forms like table sugar (sucrose), high-fructose corn syrup, and other sweeteners added to foods and beverages. Derived primarily from sugarcane and sugar beets, sugar has been used for centuries to enhance the flavor of food and preserve products. Its sweet taste makes it a popular ingredient in baked goods, desserts, sauces, and beverages, contributing significantly to the food industry.",
    para1b:"Although sugar is naturally occurring, its excessive consumption has become a global health concern due to its links with obesity, type 2 diabetes, and heart disease. This has led to increasing efforts to reduce sugar intake in processed foods and promote healthier alternatives. Despite these concerns, sugar plays an important role in the culinary world, as it not only provides sweetness but also adds texture, color, and preservation properties to various products.",
    heading2:"Benefits of Sugar",
    para2a:"While sugar has earned a bad reputation due to its association with health problems when consumed in excess, it does offer some benefits when eaten in moderation. Sugar is a quick and efficient source of energy, as it is rapidly absorbed into the bloodstream and converted into glucose, which fuels the body and brain. This makes it especially useful for athletes or individuals needing an immediate energy boost during intense physical activity. In medical settings, sugar is sometimes used in oral rehydration solutions to treat dehydration, as it helps the body absorb fluids more effectively.",
    para2b:"In cooking, sugar's ability to enhance flavors and improve the texture of food is indispensable. It aids in the fermentation process for bread and helps create the caramelization needed for browning and flavor development in baked goods. Additionally, sugar acts as a preservative in jams, jellies, and syrups, extending the shelf life of these products by inhibiting bacterial growth.",
    heading3:"Nutritional Value of Sugar",
    para3a:"Nutritionally, sugar provides 4 calories per gram, making it an energy-dense ingredient. However, sugar is often referred to as providing empty calories because it lacks essential nutrients like vitamins, minerals, and fiber. Consuming foods high in added sugars can lead to nutrient deficiencies if these foods replace more nutrient-rich options in the diet.",
    para3b:"While natural sugars found in fruits and dairy come with the added benefits of fiber, vitamins, and minerals, processed sugars contribute little beyond energy. Therefore, it’s important to limit added sugar consumption and opt for naturally occurring sugars in whole foods to maintain a balanced and healthy diet.",
   },
   {
    id:5,
    title: "Fox Nuts",
    description: "Fox nuts, commonly known as lotus seeds or makhana, are the edible seeds of the Euryale Fox plant, which thrives in the shallow...",
    image: fox_nuts,
    date: Date.now(),
    category: 'Cereals',
    heading1:"Fox Nuts: An Overview",
    para1a:"Fox nuts, commonly known as lotus seeds or makhana, are the edible seeds of the Euryale Fox plant, which thrives in the shallow waters of ponds and lakes throughout India and parts of Asia. These seeds have been a staple in traditional Indian cuisine and Ayurvedic medicine for centuries, prized for their unique flavor and texture. Typically harvested in late summer, fox nuts are available in various forms, including roasted, raw, and powdered.",
    para1b:"Their light and crunchy texture makes them a popular snack, often enjoyed as a healthier alternative to traditional fried snacks. As their popularity has surged in recent years, fox nuts have also gained recognition for their nutritional benefits, making them a favorite among health-conscious consumers.",
    heading2:"Benefits of Fox Nuts",
    para2a:"Fox nuts offer an impressive array of health benefits, contributing to their growing reputation as a superfood. One of their key advantages is their rich antioxidant content, which helps protect the body from oxidative stress and inflammation. This can reduce the risk of chronic diseases, such as heart disease and cancer.",
    para2b:"Additionally, fox nuts are low in calories and fat, making them an excellent snack option for weight management. Their high fiber content promotes digestive health, aiding in regular bowel movements and preventing constipation. Furthermore, fox nuts have a low glycemic index, which makes them suitable for people with diabetes as they help stabilize blood sugar levels.",
    heading3:"Nutritional Value of Fox Nuts",
    para3a:"Nutritionally, fox nuts are a powerhouse, offering a wealth of essential nutrients. A 100-gram serving of roasted fox nuts contains approximately 347 calories, with around 9 grams of protein and less than 1 gram of fat. They are predominantly composed of carbohydrates, providing about 76 grams per serving, which serves as a significant energy source. Fox nuts are also an excellent source of dietary fiber, with approximately 14 grams per serving, contributing to better digestive health and promoting feelings of fullness. In terms of vitamins and minerals, they are rich in magnesium, potassium, phosphorus, and calcium, all of which are vital for maintaining overall health. Incorporating fox nuts into your diet can be a delicious way to enhance nutritional intake while enjoying their unique taste and texture.",
    para3b:"Fox nuts are more than just a delightful snack; they are a versatile and nutritious addition to any diet. With their myriad health benefits and impressive nutritional profile, fox nuts are a worthy investment for anyone looking to improve their overall well-being.",
   },
   {
    id:6,
    title: "Pea Nuts",
    description: "Peanuts, often referred to as groundnuts or monkey nuts, are legumes belonging to the family Fabaceae. Native to South...",
    image: pea_nuts,
    date: Date.now(),
    category: 'Cereals',
    heading1:"Peanuts: An Overview",
    para1a:"Peanuts, often referred to as groundnuts or monkey nuts, are legumes belonging to the family Fabaceae. Native to South America, these versatile seeds are cultivated in warm climates around the world, with major producers including the United States, China, India, and Nigeria. Unlike tree nuts, peanuts grow underground and develop in pods, making them unique among other commonly consumed nuts.",
    para1b:"Peanuts can be enjoyed in various forms, including raw, roasted, or as peanut butter, and they are widely used in cooking and baking. Their rich, nutty flavor and crunchy texture make them a popular snack and an essential ingredient in many culinary traditions.",
    heading2:"Benefits of Peanuts",
    para2a:"Peanuts offer a range of health benefits, making them a nutritious addition to any diet. One of their most notable advantages is their high protein content; peanuts are an excellent plant-based protein source, providing about 25 grams per 100 grams. This makes them particularly beneficial for vegetarians and vegans seeking to meet their protein needs.",
    para2b:"Additionally, peanuts are rich in healthy fats, primarily monounsaturated and polyunsaturated fats, which are known to support heart health by helping to lower bad cholesterol levels. Their antioxidant properties, attributed to compounds such as resveratrol and flavonoids, also contribute to reducing inflammation and the risk of chronic diseases.",
    heading3:"Nutritional Value of Peanuts",
    para3a:"Nutritionally, peanuts are packed with essential vitamins and minerals. A 100-gram serving of peanuts contains approximately 567 calories, along with 25 grams of protein and 49 grams of fat. Despite their high fat content, the majority of fats in peanuts are heart-healthy unsaturated fats. Peanuts are also an excellent source of dietary fiber, providing around 8 grams per serving, which aids in digestion and helps maintain a healthy weight. Furthermore, peanuts contain vital nutrients such as vitamin E, magnesium, phosphorus, and folate, all of which play crucial roles in maintaining overall health. Their combination of protein, healthy fats, and fiber makes peanuts a satisfying and nutrient-dense snack that can help curb hunger and promote long-lasting energy.",
    para3b:"Peanuts are more than just a tasty snack; they offer a wealth of health benefits and essential nutrients. With their unique growth characteristics, delicious flavor, and versatility in various dishes, peanuts can easily fit into a balanced diet, providing both enjoyment and nourishment.",
   },
   {
    id:7,
    title: "Lakdong Turmeric",
    description: "Lakdong turmeric, known scientifically as Curcuma longa, is a prized variety of turmeric originating from the Lakdong...",
    image: lakdong_turmeric,
    date: Date.now(),
    category: 'Spices',
    heading1:"Lakdong Turmeric: An Overview",
    para1a:"Lakdong turmeric, known scientifically as Curcuma longa, is a prized variety of turmeric originating from the Lakdong region in India’s northeastern state of Meghalaya. This specific type of turmeric is renowned for its vibrant yellow color, intense aroma, and high curcumin content, which is the active compound responsible for its health benefits. Lakdong turmeric is primarily cultivated in the rich, fertile soil of the region, and its cultivation practices often involve traditional methods that enhance its quality. Used extensively in Indian cuisine, Lakdong turmeric is also celebrated in Ayurvedic medicine for its therapeutic properties, making it a valuable addition to both culinary and health applications.",
    heading2:"Benefits of Lakdong Turmeric",
    para2a:"Lakdong turmeric offers numerous health benefits, primarily attributed to its high curcumin content. Curcumin is a powerful antioxidant with anti-inflammatory properties, making it effective in reducing inflammation and providing relief from conditions such as arthritis and joint pain. Regular consumption of Lakdong turmeric can also support the immune system, enhance liver function, and improve digestive health.",
    para2b:"Additionally, its potential neuroprotective effects have garnered attention in recent research, suggesting that curcumin may help improve cognitive function and reduce the risk of neurodegenerative diseases like Alzheimer's. The traditional use of turmeric in skincare is also notable; its antimicrobial and anti-inflammatory properties make it a popular ingredient in natural beauty treatments for promoting healthy skin.",
    heading3:"Nutritional Value of Lakdong Turmeric",
    para3a:"Nutritionally, Lakdong turmeric is low in calories yet packed with essential vitamins and minerals. A typical serving of dried turmeric powder (approximately 1 tablespoon) contains about 24 calories, 0.5 grams of fat, and 1 gram of protein. The real nutritional value lies in its bioactive compounds, primarily curcumin, which can comprise 3-5% of the turmeric root. Besides curcumin, Lakdong turmeric is also a source of various vitamins, including vitamin C, vitamin E, and several B vitamins, all of which contribute to overall health. Additionally, it contains minerals such as manganese, iron, and potassium. When combined with black pepper, which contains piperine, the bioavailability of curcumin significantly increases, enhancing its absorption and effectiveness in the body.",
    para3b:"Lakdong turmeric is more than just a spice; it is a powerful ingredient with a rich history and a myriad of health benefits. Whether used in cooking, as a dietary supplement, or in natural beauty treatments, Lakdong turmeric stands out for its vibrant color, unique flavor, and therapeutic properties, making it a valuable addition to any health-conscious lifestyle.",
   },
   {
    id:8,
    title: "Cardamom",
    description: "Cardamom, often referred to as the 'queen of spices,' is a highly aromatic spice derived from the seeds of plants belonging...",
    image: cardamom_spice,
    date: Date.now(),
    category: 'Spices',
    heading1:"",
    para1a:"Cardamom, often referred to as the 'queen of spices,' is a highly aromatic spice derived from the seeds of plants belonging to the Zingiberaceae family, primarily the species Elettaria cardamomum and Amomum subulatum. Originating from the lush forests of India, cardamom has been cherished for centuries for its unique flavor, fragrance, and numerous health benefits. The spice is typically available in two main forms: green cardamom, known for its sweet and spicy flavor, and black cardamom, which has a smokier, more robust taste. Used extensively in Indian, Middle Eastern, and Scandinavian cuisines, cardamom adds depth to both savory dishes and desserts, making it a versatile ingredient in various culinary traditions.",
    heading2:"Benefits of Cardamom",
    para2a:"Cardamom boasts a remarkable array of health benefits, contributing to its status as a revered spice in traditional medicine. Rich in antioxidants, cardamom helps combat oxidative stress and may reduce inflammation in the body. This can aid in lowering the risk of chronic diseases, including heart disease and cancer. Additionally, cardamom is known for its digestive properties; it can help alleviate indigestion, bloating, and gas. The spice also has antimicrobial properties, which can support oral health by fighting bacteria that cause bad breath and other oral infections. Furthermore, some studies suggest that cardamom may help regulate blood pressure and improve overall cardiovascular health, making it a beneficial addition to a heart-healthy diet.",
    heading3:"Nutritional Value of Cardamom",
    para3a:"Nutritionally, cardamom is low in calories but rich in essential nutrients. A 100-gram serving of cardamom provides approximately 311 calories, along with significant amounts of carbohydrates, dietary fiber, and healthy fats. Cardamom is also a source of several vitamins and minerals, including vitamin C, vitamin B6, calcium, magnesium, and potassium. These nutrients play crucial roles in maintaining overall health, supporting metabolic functions, and promoting healthy bones and muscles. The presence of essential oils, such as cineole and limonene, contributes to cardamom's distinct flavor and aroma, while also providing additional health benefits. Incorporating cardamom into your daily diet can enhance not only the flavor of your meals but also your overall well-being.",
    para3b:"Cardamom is a delightful spice with a rich history and an impressive profile of health benefits and nutritional value. Whether used in cooking, baking, or as a natural remedy, cardamom's unique flavor and numerous health advantages make it an excellent addition to any kitchen and a valuable asset for those seeking to enhance their health through diet.",
   },
   {
    id:9,
    title: "Clove",
    description: "Clove, scientifically known as Syzygium aromaticum, is a highly aromatic spice derived from the flower buds of a tree...",
    image: clove_spice,
    date: Date.now(),
    category: 'Spices',
    heading1:"Clove: An Overview",
    para1a:"Clove, scientifically known as Syzygium aromaticum, is a highly aromatic spice derived from the flower buds of a tree native to the Maluku Islands in Indonesia. Known for its intense flavor and distinct fragrance, clove is a popular ingredient in various culinary traditions worldwide, particularly in Asian, Middle Eastern, and African cuisines. These dried flower buds are typically used whole or ground into powder, imparting a warm, sweet, and slightly bitter taste to dishes. Beyond its culinary uses, clove has a rich history in traditional medicine, where it has been valued for its numerous health benefits and therapeutic properties.",
    heading2:"Benefits of Clove",
    para2a:"Clove is renowned for its powerful medicinal properties, largely attributed to its high concentration of eugenol, a natural compound with strong antioxidant and anti-inflammatory effects. This makes clove particularly effective in combating oxidative stress and reducing inflammation, which can help prevent chronic diseases such as heart disease and diabetes. Clove is also celebrated for its antiseptic properties; it has been traditionally used to alleviate dental pain and improve oral health by combating harmful bacteria in the mouth. Additionally, clove may aid in digestion, helping to relieve issues such as bloating and gas. Its potential to boost the immune system further underscores clove’s role as a natural remedy for various ailments.",

    heading3:"Nutritional Value of Clove",
    para3a:"Nutritionally, cloves are incredibly rich in essential nutrients despite being used in small quantities. A 100-gram serving of ground cloves contains approximately 274 calories, with most of the calories coming from carbohydrates. Cloves are also an excellent source of dietary fiber, providing around 24 grams per serving, which supports digestive health. Additionally, they are rich in vitamins and minerals, including vitamin C, vitamin K, manganese, and calcium. Manganese, in particular, plays a crucial role in bone health and metabolism. The unique flavor profile and nutritional benefits of cloves make them a valuable addition to various dishes, enhancing both taste and health.",
    para3b:"Clove is a remarkable spice with a rich history and an impressive array of health benefits and nutritional value. Whether used to elevate the flavors of savory dishes, desserts, or beverages, or as a natural remedy for various health concerns, clove remains an essential ingredient in kitchens and traditional medicine cabinets around the world.",
   },
   {
    id:10,
    title: "Cumin",
    description: "Cumin, scientifically known as Cuminum cyminum, is a spice that originates from the Mediterranean region and South Asia. Its seeds...",
    image: cumin_masala,
    date: Date.now(),
    category: 'Spices',
    heading1:"Cumin: An Overview",
    para1a:"Cumin, scientifically known as Cuminum cyminum, is a spice that originates from the Mediterranean region and South Asia. Its seeds, characterized by their distinctive crescent shape and earthy, warm flavor, are a staple in many culinary traditions worldwide, including Indian, Middle Eastern, and Mexican cuisines. Cumin is often used both whole and ground, lending a rich, aromatic quality to a variety of dishes, from curries and stews to spice blends like garam masala and taco seasoning. Aside from its culinary appeal, cumin has a long history of use in traditional medicine, celebrated for its numerous health benefits and therapeutic properties.",
    heading2:"Benefits of Cumin",
    para2a:"Cumin is packed with health benefits that extend beyond its delicious flavor. One of its most notable advantages is its ability to aid digestion. Cumin seeds are known to stimulate the secretion of digestive enzymes, helping to alleviate common gastrointestinal issues such as bloating, gas, and indigestion. Additionally, cumin has been found to have antimicrobial properties, which may help combat harmful bacteria and promote gut health. Research also suggests that cumin can support weight loss efforts by enhancing metabolic rates and reducing body fat. Furthermore, the spice is rich in antioxidants, which play a crucial role in protecting the body from oxidative stress and inflammation, potentially lowering the risk of chronic diseases.",
    heading3:"Nutritional Value of Cumin",
    para3a:"Nutritionally, cumin seeds are a powerhouse of essential nutrients. A 100-gram serving of ground cumin contains approximately 375 calories, predominantly from carbohydrates and healthy fats. Cumin is an excellent source of dietary fiber, providing around 10 grams per serving, which aids in digestion and promotes feelings of fullness. In terms of vitamins and minerals, cumin is rich in iron, providing about 66% of the recommended daily intake in a 100-gram serving. This makes it particularly beneficial for individuals at risk of iron deficiency, such as vegetarians and pregnant women. Additionally, cumin contains significant amounts of manganese, magnesium, and calcium, all of which contribute to overall health and well-being.",
    para3b:"Cumin is a versatile spice that not only enhances the flavor of various dishes but also offers a myriad of health benefits and nutritional value. Whether used in cooking, baking, or as a natural remedy, cumin remains a beloved ingredient in kitchens around the world, making it an essential addition to a healthy and flavorful diet.",
   },
   {
    id:11,
    title: "Fenugreek Seeds",
    description: "Fenugreek seeds, derived from the plant Trigonella foenum-graecum, are small, golden-brown seeds that have been used...",
    image: fenugreek_spice,
    date: Date.now(),
    category: 'Spices',
    heading1:"Fenugreek Seeds: An Overview",
    para1a:"Fenugreek seeds, derived from the plant Trigonella foenum-graecum, are small, golden-brown seeds that have been used for centuries in culinary and medicinal practices, particularly in South Asian and Mediterranean cuisines. The seeds have a distinctive slightly bitter flavor and a strong aroma, often described as nutty and sweet. They can be used whole or ground into powder and are commonly incorporated into spice blends, curries, and bread. Beyond their culinary applications, fenugreek seeds have gained attention for their numerous health benefits, making them a valuable ingredient in both kitchens and traditional medicine.",
    heading2:"Benefits of Fenugreek Seeds",
    para2a:"Fenugreek seeds are celebrated for their wide range of health benefits. One of the most notable is their potential to regulate blood sugar levels, making them particularly beneficial for individuals with diabetes. Studies suggest that fenugreek seeds may improve insulin sensitivity and reduce blood sugar levels after meals. Additionally, fenugreek is known for its ability to enhance digestive health; it can help alleviate symptoms of indigestion, bloating, and constipation. The seeds are also rich in antioxidants, which help combat oxidative stress in the body. Furthermore, fenugreek is often used to support lactation in breastfeeding mothers, as it may increase milk production. Its anti-inflammatory properties also make it effective in soothing conditions like arthritis and other inflammatory ailments.",
    heading3:"Nutritional Value of Fenugreek Seeds",
    para3a:"Nutritionally, fenugreek seeds are a powerhouse of essential nutrients. A 100-gram serving of fenugreek seeds contains approximately 323 calories, primarily from carbohydrates and healthy fats. They are an excellent source of protein, providing around 23 grams per serving, making them beneficial for vegetarians and vegans seeking to meet their protein needs. Additionally, fenugreek seeds are rich in dietary fiber, with about 25 grams per serving, which supports digestive health and promotes feelings of fullness. In terms of vitamins and minerals, they are a significant source of iron, magnesium, manganese, and vitamin B6, all of which are crucial for overall health. The presence of phytonutrients, such as saponins and alkaloids, further enhances the health benefits of fenugreek seeds.",
    para3b:"Fenugreek seeds are not only a flavorful addition to various dishes but also offer an impressive array of health benefits and nutritional value. Whether used in cooking, as a supplement, or in traditional remedies, fenugreek seeds provide a wealth of advantages that make them a valuable asset in any diet. Their versatility and health-promoting properties continue to secure their place as a staple ingredient in kitchens and health practices around the world.",
   },
   {
    id:12,
    title: "Red Chilly",
    description: "Red chilly, derived from the Capsicum species, is a vibrant spice that adds heat and flavor to cuisines worldwide...",
    image: red_chilli,
    date: Date.now(),
    category: 'Spices',
    heading1:"Red Chilly: An Overview",
    para1a:"Red chilly, derived from the Capsicum species, is a vibrant spice that adds heat and flavor to cuisines worldwide. These fiery peppers are available in various forms, including fresh, dried, crushed, and powdered, with different varieties ranging from mild to extremely hot. Commonly used in dishes from Indian, Mexican, and Thai cuisines, red chili not only enhances flavor but also serves as a key ingredient in popular spice blends like chili powder and curry powder. Beyond its culinary applications, red chili has a rich history in traditional medicine, celebrated for its potential health benefits and versatility.",
    heading2:"Benefits of Red Chilly",
    para2a:"Red chilly offers an array of health benefits primarily due to its active compound, capsaicin, which is responsible for its heat. Capsaicin has been shown to possess anti-inflammatory properties, making it effective in alleviating pain associated with conditions like arthritis and muscle soreness. Additionally, red chili can boost metabolism, promoting weight loss by increasing energy expenditure and fat oxidation. Some studies suggest that capsaicin may help reduce hunger and control appetite, further supporting weight management. Furthermore, red chili is rich in antioxidants, particularly vitamin C and carotenoids, which help combat oxidative stress in the body and strengthen the immune system.",
    heading3:"Nutritional Value of Red Chilly",
    para3a:"Nutritionally, red chili peppers are low in calories but packed with essential nutrients. A 100-gram serving of raw red chili contains approximately 40 calories, with a significant amount of carbohydrates, primarily in the form of fiber. Red chili is an excellent source of vitamins A, C, and E, which are crucial for maintaining healthy skin and immune function. Additionally, it provides essential minerals such as potassium and magnesium, which support heart health and muscle function. The capsaicin content in red chili also contributes to its health benefits, promoting better circulation and potentially lowering blood pressure. Including red chili in your diet not only enhances the flavor of your meals but also provides a wealth of nutritional advantages.",
    para3b:"Red chilly is a dynamic spice that not only elevates the taste of various dishes but also offers numerous health benefits and nutritional value. Whether used to spice up a curry, add heat to sauces, or enhance the flavor of grilled meats and vegetables, red chili remains a staple ingredient in kitchens around the world. Its versatility and health-promoting properties make it a valuable addition to a balanced diet, providing both flavor and wellness.",
   },
   {
    id:13,
    title: "Fennel",
    description: "Fennel, scientifically known as Foeniculum vulgare, is a flavorful and aromatic herb native to the Mediterranean...",
    image: fennel_seeds,
    date: Date.now(),
    category: 'Spices',
    heading1:"Fennel: An Overview",
    para1a:"Fennel, scientifically known as Foeniculum vulgare, is a flavorful and aromatic herb native to the Mediterranean region. Often recognized by its feathery green fronds and bulbous base, fennel is a versatile plant used in various culinary applications. Its sweet, anise-like flavor makes it a popular ingredient in salads, soups, and sauces, as well as a key component in spice blends. Both the bulb and the seeds of fennel are edible, and they offer distinct flavors that enhance a variety of dishes. Beyond its culinary uses, fennel has a rich history in traditional medicine, where it has been valued for its health-promoting properties.",
    heading2:"Benefits of Fennel",
    para2a:"Fennel is renowned for its numerous health benefits, many of which stem from its unique compounds. One of the most significant advantages of fennel is its ability to aid digestion. It has been traditionally used to relieve bloating, gas, and other gastrointestinal discomforts. The essential oils in fennel, such as anethole, have been shown to possess anti-inflammatory and antispasmodic properties, making it effective in soothing digestive tract muscles. Additionally, fennel seeds are often chewed after meals to freshen breath and promote healthy digestion. Beyond digestive health, fennel is rich in antioxidants, which help combat oxidative stress and may reduce the risk of chronic diseases. Its potential to balance hormonal levels and alleviate menstrual discomfort has also made it a popular choice among women’s health remedies.",
    heading3:"Nutritional Value of Fennel",
    para3a:"Nutritionally, fennel is low in calories yet packed with essential nutrients. A 100-gram serving of raw fennel contains approximately 31 calories, along with a wealth of vitamins and minerals. It is an excellent source of vitamin C, providing about 12% of the recommended daily intake, which supports immune function and skin health. Fennel is also rich in dietary fiber, with approximately 3 grams per serving, promoting digestive health and aiding in weight management. Additionally, it contains essential minerals like potassium, calcium, and magnesium, all of which contribute to overall health and well-being. The combination of its unique flavor and impressive nutritional profile makes fennel a valuable addition to a balanced diet.",
    para3b:"Fennel is a delightful herb that enhances the flavor of various dishes while offering a myriad of health benefits and nutritional value. Whether enjoyed raw in salads, roasted as a side dish, or brewed as a tea, fennel stands out as a versatile ingredient that promotes health and wellness. Its rich history in both culinary and medicinal uses continues to secure its place as a staple herb in kitchens and natural remedies around the world.",
   },
   {
    id:14,
    title: "Corainder",
    description: "Coriander, scientifically known as Coriandrum sativum, is a versatile herb native to regions spanning from Southern...",
    image: coriander_spice,
    date: Date.now(),
    category: 'Spices',
    heading1:"Coriander: An Overview",
    para1a:"Coriander, scientifically known as Coriandrum sativum, is a versatile herb native to regions spanning from Southern Europe to North Africa and Southwestern Asia. Also known as cilantro (the term commonly used for its fresh leaves) and coriander (referring to the seeds), this herb is widely utilized in various culinary traditions around the globe. The leaves are often used fresh in salads, salsas, and garnishes, while the seeds, which have a warm, spicy flavor, are ground into powder or used whole in spice blends. Coriander's distinctive aroma and flavor make it a staple in cuisines such as Indian, Middle Eastern, and Latin American, where it adds depth and freshness to a wide range of dishes.",
    heading2:"Benefits of Coriander",
    para2a:"Coriander is not only valued for its flavor but also for its numerous health benefits. One of the most significant advantages of coriander is its potential to aid digestion. The herb has been traditionally used to alleviate digestive issues, such as bloating and gas, thanks to its carminative properties. Additionally, coriander is rich in antioxidants, which help combat oxidative stress and may reduce the risk of chronic diseases like heart disease and diabetes. The essential oils found in coriander, including linalool and borneol, possess antimicrobial properties that can help fight off infections. Some studies suggest that coriander may also have anti-inflammatory effects, potentially reducing inflammation and supporting joint health.",
    heading3:"Nutritional Value of Coriander",
    para3a:"",
    para3b:"",
   },
   {
    id:15,
    title: "Black Pepper",
    description: "Black pepper, scientifically known as Piper nigrum, is one of the most widely used spices in the world, often referred...",
    image: black_pepper,
    date: Date.now(),
    category: 'Spices',
    heading1:"Black Pepper: An Overview",
    para1a:"Black pepper, scientifically known as Piper nigrum, is one of the most widely used spices in the world, often referred to as the 'king of spices.' Native to the tropical regions of India, it has a long history of use that dates back thousands of years, both as a culinary ingredient and a valuable trading commodity. Black pepper is made from the unripe berries of the pepper plant, which are picked, cooked, and dried to create the small, dark, wrinkled peppercorns we know today. Its robust, pungent flavor and versatility make it a staple seasoning in various cuisines, enhancing everything from savory dishes to sauces and marinades.",
    heading2:"Benefits of Black Pepper",
    para2a:"Beyond its culinary applications, black pepper is renowned for its numerous health benefits. One of its most notable compounds is piperine, which not only gives black pepper its characteristic heat but also offers powerful antioxidant and anti-inflammatory properties. Piperine has been shown to enhance the bioavailability of certain nutrients and compounds, such as curcumin from turmeric, making them more effective in the body. Additionally, black pepper can aid digestion by stimulating the production of digestive enzymes and promoting gut health. It has also been linked to improved respiratory health, as its pungent nature may help clear nasal passages and alleviate symptoms of congestion.",
    heading3:"Nutritional Value of Black Pepper",
    para3a:"Nutritionally, black pepper is low in calories but rich in essential vitamins and minerals. A 100-gram serving of black pepper contains approximately 255 calories, primarily from carbohydrates and fats. It is an excellent source of manganese, providing over 100% of the recommended daily intake in a single serving, which is crucial for metabolism and bone health. Black pepper also contains significant amounts of iron, potassium, and vitamin K, all of which contribute to overall health and well-being. Furthermore, the antioxidant properties of black pepper can help protect the body against oxidative stress, potentially lowering the risk of chronic diseases.",
    para3b:"Black Pepper is more than just a flavor enhancer; it is a spice packed with health benefits and nutritional value. Whether used to season a dish, improve digestion, or boost the absorption of other nutrients, black pepper remains a cherished ingredient in kitchens around the world. Its versatility and medicinal properties ensure that it continues to hold a prominent place in both culinary and holistic practices, making it a truly indispensable spice.",
   },
   {
    id:16,
    title: "White Pepper",
    description: "White pepper, derived from the same plant as black pepper (Piper nigrum), is a spice that has a milder, more earthy flavor...",
    image: white_pepper,
    date: Date.now(),
    category: 'Spices',
    heading1:"White Pepper: An Overview",
    para1a:"White pepper, derived from the same plant as black pepper (Piper nigrum), is a spice that has a milder, more earthy flavor compared to its more pungent counterpart. The primary difference between black and white pepper lies in the processing method. While black pepper is made from the unripe berries, white pepper is produced by soaking ripe berries in water to ferment, after which the outer skin is removed, leaving only the inner seed. This process gives white pepper its characteristic pale color and distinct taste, making it a popular choice in various culinary applications, particularly in Asian and European cuisines. It is often used in soups, sauces, and creamy dishes where the dark specks of black pepper would be visually unappealing.",
    
    heading2:"Benefits of White Pepper",
    para2a:"White pepper offers several health benefits, many of which are attributed to its active compound, piperine, which is also present in black pepper. Piperine is known for its antioxidant and anti-inflammatory properties, contributing to overall health by combating oxidative stress in the body.",
    para2b:"Additionally, white pepper may aid digestion by stimulating the production of digestive enzymes and improving gut health. It has also been traditionally used to relieve headaches and nasal congestion due to its ability to promote circulation and clear the sinuses. Moreover, some studies suggest that piperine may enhance the bioavailability of certain nutrients and medications, making them more effective in the body.",
    heading3:"Nutritional Value of White Pepper",
    para3a:"Nutritionally, white pepper is low in calories while being rich in essential nutrients. A 100-gram serving of white pepper contains approximately 295 calories, primarily from carbohydrates and healthy fats. It is a good source of dietary fiber, which aids in digestion and promotes a healthy gut. White pepper also contains essential vitamins and minerals, including manganese, iron, and potassium. Manganese plays a vital role in metabolism and bone health, while potassium is crucial for maintaining healthy blood pressure levels. Additionally, the presence of antioxidants in white pepper can help protect the body from chronic diseases by reducing inflammation and oxidative damage.",
    para3b:"White Pepper is a versatile spice that enhances the flavor of various dishes while offering a range of health benefits and nutritional value. Its unique processing method and milder flavor make it an ideal choice for recipes where a subtler spice is desired. Whether used in cooking or as a natural remedy, white pepper remains an essential ingredient in kitchens and health practices worldwide, contributing to both culinary delight and overall wellness.",
   },
   {
    id:17,
    title: "Bay Leaves Powder",
    description: "Bay leaves, derived from the Laurus nobilis tree, are aromatic leaves commonly used in cooking to enhance flavor. Native to the...",
    image: bay_powder,
    date: Date.now(),
    category: 'Spices',
    heading1:"Bay Leaves: An Overview",
    para1a:"Bay leaves, derived from the Laurus nobilis tree, are aromatic leaves commonly used in cooking to enhance flavor. Native to the Mediterranean region, bay leaves have a long history of culinary and medicinal uses, dating back to ancient Greece and Rome, where they were used to crown victors in athletic competitions. The leaves are typically dried before use, imparting a unique, slightly floral and herbal aroma to dishes. Bay leaves are a staple in many cuisines, especially in soups, stews, and sauces, where they are often used whole and removed before serving. Their ability to enhance the flavors of various ingredients makes them a beloved herb in kitchens around the world.",
    heading2:"Benefits of Bay Leaves",
    para2a:"Bay leaves offer several health benefits, primarily attributed to their rich content of essential oils and antioxidants. One notable component, eugenol, is known for its anti-inflammatory and antimicrobial properties, which may help boost overall health and reduce the risk of infections. Additionally, bay leaves are traditionally used to aid digestion; they can help alleviate symptoms of bloating, gas, and indigestion by promoting healthy digestion and the production of digestive enzymes. Moreover, bay leaves are believed to possess calming effects that may help reduce anxiety and promote relaxation, making them beneficial for mental well-being.",
    heading3:"Nutritional Value of Bay Leaves",
    para3a:"Nutritionally, bay leaves are low in calories but packed with essential vitamins and minerals. A 100-gram serving of dried bay leaves contains about 313 calories, but it's important to note that they are typically used in small amounts due to their intense flavor. Bay leaves are a rich source of vitamins A, C, and several B vitamins, including folate and pyridoxine, which are essential for maintaining overall health. They also contain important minerals such as calcium, iron, magnesium, and potassium, contributing to bone health, muscle function, and cardiovascular health. Furthermore, the antioxidants found in bay leaves help combat oxidative stress in the body, potentially reducing the risk of chronic diseases.",
    para3b:"Bay leaves are more than just a flavorful addition to dishes; they also offer a range of health benefits and nutritional value. Their unique aroma and taste make them a versatile herb that enhances various cuisines, while their potential health-promoting properties support digestive health and overall well-being. Whether used in cooking or as a natural remedy, bay leaves remain a cherished ingredient in culinary traditions and holistic practices worldwide.",
   },
   {
    id:18,
    title: "Grapes",
    description: "Grapes, belonging to the genus Vitis, are small, sweet, and juicy fruits that have been cultivated for thousands of years...",
    image: grapes_fruit,
    date: Date.now(),
    category: 'Fruits',
    heading1:"Grapes: An Overview",
    para1a:"Grapes, belonging to the genus Vitis, are small, sweet, and juicy fruits that have been cultivated for thousands of years, making them one of the oldest cultivated fruits in the world. They come in a variety of colors, including green, red, and black, and can be enjoyed fresh or dried as raisins. Grapes are not only popular for their taste but also for their versatility in culinary applications. They are used to make a wide range of products, including wines, juices, jellies, and vinegar. Grapes grow in clusters on vines and thrive in warm climates, making them a staple fruit in many regions, especially in Mediterranean and temperate areas.",
    heading2:"Benefits of Grapes",
    para2a:"Grapes are celebrated for their numerous health benefits, largely attributed to their rich content of antioxidants, vitamins, and minerals. One of the most notable compounds found in grapes is resveratrol, a powerful antioxidant linked to various health benefits, including improved heart health and reduced inflammation. Regular consumption of grapes has been associated with a lower risk of chronic diseases such as heart disease and diabetes. Additionally, grapes may support healthy digestion due to their high fiber content, which helps maintain regular bowel movements and promotes gut health. They also contain natural sugars, making them a healthy alternative to processed sweets, providing quick energy without the added refined sugars.",
    heading3:"Nutritional Value of Grapes",
    para3a:"Nutritionally, grapes are low in calories but rich in essential vitamins and minerals. A 100-gram serving of grapes contains approximately 69 calories, primarily from carbohydrates, mainly natural sugars. They are an excellent source of vitamins C and K, both of which play crucial roles in immune function and bone health. Grapes also provide a good amount of antioxidants, including flavonoids and phenolic acids, which help protect the body from oxidative stress and inflammation. Furthermore, they contain essential minerals such as potassium, which is vital for maintaining healthy blood pressure levels and supporting heart function. The hydrating nature of grapes, consisting of about 81% water, makes them a refreshing and nutritious snack.",
    para3b:"Grapes are a delicious and versatile fruit that offers a wealth of health benefits and nutritional value. Their natural sweetness, combined with their rich antioxidant content, makes them an excellent addition to a balanced diet. Whether enjoyed fresh, dried, or as part of a beverage, grapes continue to be a beloved fruit around the world, celebrated for both their taste and health-promoting properties.",
   },
   {
    id:19,
    title: "Pomegranate",
    description: "Pomegranate, scientifically known as Punica granatum, is a striking fruit renowned for its vibrant ruby-red seeds, which are packed...",
    image: pome_fruit,
    date: Date.now(),
    category: 'Fruits',
    heading1:"Pomegranate: An Overview",
    para1a:"Pomegranate, scientifically known as Punica granatum, is a striking fruit renowned for its vibrant ruby-red seeds, which are packed with juice and flavor. Native to the Mediterranean region and parts of Asia, pomegranates have been cultivated for thousands of years, symbolizing abundance and fertility in various cultures. The fruit's hard outer skin conceals numerous arils (the juicy seeds), making it not only a nutritious snack but also a visually appealing addition to dishes. Pomegranates are commonly used in juices, salads, and desserts, offering a sweet-tart flavor that enhances a variety of culinary creations.",
    heading2:"Benefits of Pomegranate",
    para2a:"Pomegranates are celebrated for their numerous health benefits, largely attributed to their rich content of antioxidants, vitamins, and minerals. One of the most notable compounds found in pomegranates is punicalagins, which are powerful antioxidants that help combat oxidative stress and inflammation in the body. Regular consumption of pomegranate has been linked to improved heart health by reducing blood pressure, lowering cholesterol levels, and improving overall cardiovascular function. Additionally, studies suggest that pomegranates may have anti-cancer properties, particularly in prostate and breast cancers, by inhibiting tumor growth and reducing the spread of cancer cells. The anti-inflammatory properties of pomegranates can also aid in relieving symptoms of arthritis and other inflammatory conditions.",
    heading3:"Nutritional Value of Pomegranate",
    para3a:"Nutritionally, pomegranates are a powerhouse of essential vitamins and minerals while being relatively low in calories. A 100-gram serving of pomegranate contains about 83 calories, primarily from carbohydrates, mainly natural sugars and dietary fiber. Pomegranates are an excellent source of vitamin C, providing about 17% of the recommended daily intake, which supports immune health and skin vitality. They are also rich in vitamin K, essential for blood clotting and bone health, as well as several B vitamins that play key roles in energy metabolism. Furthermore, pomegranates provide important minerals such as potassium and magnesium, which are vital for maintaining healthy blood pressure and heart function. The high antioxidant content in pomegranates helps protect the body from free radical damage, potentially lowering the risk of chronic diseases.",
    para3b:"Pomegranates are not only a delicious and visually appealing fruit but also a nutrient-dense superfood that offers a wealth of health benefits. Their unique flavor and impressive nutritional profile make them a valuable addition to a balanced diet. Whether enjoyed fresh, juiced, or incorporated into dishes, pomegranates continue to be cherished for their taste and remarkable contributions to health and wellness.",
   },
   {
    id:20,
    title: "Mango",
    description: "Mango, often referred to as the 'king of fruits,' is a tropical fruit belonging to the Mangifera indica species, native to...",
    image: mango_fruit,
    date: Date.now(),
    category: 'Fruits',
    heading1:"Mango: An Overview",
    para1a:"Mango, often referred to as the 'king of fruits,' is a tropical fruit belonging to the Mangifera indica species, native to South Asia but now cultivated in many warm climates around the world. Known for its juicy, sweet, and slightly tangy flavor, mangoes are a beloved fruit enjoyed in various forms—fresh, dried, juiced, or incorporated into smoothies, desserts, and salads. With their bright orange-yellow flesh and luscious texture, mangoes are not only a treat for the taste buds but also an important cultural symbol in countries like India, where they have been revered for centuries. Beyond their delightful taste, mangoes have a long history of use in traditional medicine, praised for their health-promoting properties.",
    heading2:"Benefits of Mango",
    para2a:"Mangoes offer a wide range of health benefits, largely due to their rich content of vitamins, minerals, and antioxidants. One of the key health advantages of mango is its high vitamin C content, which helps boost the immune system, promotes healthy skin, and supports tissue repair. Mangoes are also a good source of dietary fiber, aiding in digestion and helping to prevent constipation. Additionally, the fruit contains bioactive compounds such as mangiferin, a potent antioxidant that may help reduce inflammation and protect the body from oxidative stress. Regular consumption of mango has been associated with improved heart health, as the potassium and magnesium content can help regulate blood pressure and support cardiovascular function.",
    heading3:"Nutritional Value of Mango",
    para3a:"Nutritionally, mangoes are a powerhouse of essential nutrients. A 100-gram serving of fresh mango provides approximately 60 calories, mostly from carbohydrates, making it an energy-boosting snack. Mangoes are rich in vitamins A and C—vitamin A, in the form of beta-carotene, promotes healthy vision, skin, and immune function, while vitamin C helps fight off infections and keeps skin glowing. Mangoes also contain small amounts of vitamin E and several B vitamins, including folate, which is important for cell function and tissue growth. Additionally, mangoes are a good source of potassium and magnesium, which are essential for maintaining healthy blood pressure levels and supporting nerve and muscle function.",
    para3b:"Mangoes are not only a delicious and versatile fruit but also a nutritional powerhouse that offers numerous health benefits. Their sweet, tropical flavor and rich nutrient profile make them a favorite in many households around the world. Whether eaten on their own, blended into smoothies, or added to salads, mangoes remain a cherished fruit for both their taste and their ability to promote overall health and well-being.",
   },
   {
    id:21,
    title: "Banana",
    description: "Bananas, one of the most popular and widely consumed fruits worldwide, belong to the genus Musa and are native to...",
    image: banana_fruit,
    date: Date.now(),
    category: 'Fruits',
    heading1:"Banana: An Overview",
    para1a:"Bananas, one of the most popular and widely consumed fruits worldwide, belong to the genus Musa and are native to Southeast Asia. Over time, they have spread across tropical and subtropical regions, becoming a staple food in many cultures. Known for their elongated shape, smooth yellow peel, and soft, sweet flesh, bananas are enjoyed as a convenient and nutritious snack. They are a versatile fruit that can be eaten raw, blended into smoothies, used in baking, or even fried. The accessibility, portability, and naturally sweet taste of bananas make them a favorite for people of all ages.",
    heading2:"Benefits of Bananas",
    para2a:"Bananas offer a wide range of health benefits due to their high nutrient content. One of the most significant advantages is their ability to provide a quick source of energy, making them ideal for athletes or anyone needing a natural boost throughout the day. Bananas are rich in dietary fiber, particularly pectin, which helps improve digestion by regulating bowel movements and promoting gut health. Additionally, they contain natural compounds that can help soothe heartburn and protect against stomach ulcers. Bananas are also known to be mood enhancers, as they contain tryptophan, an amino acid that the body converts into serotonin, a neurotransmitter that promotes feelings of well-being and happiness.",
    heading3:"Nutritional Value of Bananas",
    para3a:"Nutritionally, bananas are a powerhouse of essential vitamins and minerals. A medium-sized banana (about 118 grams) contains around 105 calories, making it a low-calorie, nutrient-dense snack. Bananas are an excellent source of potassium, with one banana providing approximately 9% of the daily recommended intake, which helps regulate blood pressure and supports heart health. They also contain vitamin C, vitamin B6, and magnesium, all of which contribute to overall health. Vitamin B6 is particularly important for brain function and the production of red blood cells, while magnesium plays a role in muscle and nerve function. The natural sugars in bananas, such as glucose, fructose, and sucrose, provide a sustained energy release, making them a perfect pre- or post-workout snack.",
    para3b:"Bananas are a versatile, nutritious, and delicious fruit that offers numerous health benefits. Whether enjoyed on their own, as part of a meal, or in a smoothie, bananas provide essential nutrients that support heart health, digestion, and overall well-being. Their convenience and impressive nutritional profile make them a staple fruit in households around the world.",
   },
   {
    id:22,
    title: "Potatoes",
    description: "Potatoes, scientifically known as Solanum tuberosum, are one of the most widely consumed and versatile vegetables globally. Native to...",
    image: potato_veg,
    date: Date.now(),
    category: 'Vegetables',
    heading1:"Potatoes: An Overview",
    para1a:"Potatoes, scientifically known as Solanum tuberosum, are one of the most widely consumed and versatile vegetables globally. Native to the Andean region of South America, potatoes have become a staple food in many cultures due to their adaptability in cooking and their ability to grow in diverse climates. Potatoes come in various types, including russet, red, yellow, and purple, each offering unique textures and flavors. They are used in countless dishes, from mashed potatoes to fries, soups, and stews, and can be baked, boiled, roasted, or fried. This humble tuber plays a central role in many diets, providing a hearty and affordable source of energy.",
    heading2:"Benefits of Potatoes",
    para2a:"Potatoes are often misunderstood in terms of their health benefits, but they are packed with essential nutrients that contribute to overall well-being. One of their most significant advantages is their high potassium content, which helps maintain healthy blood pressure and supports heart function. Potatoes also contain resistant starch, a type of fiber that can improve digestive health by promoting the growth of beneficial gut bacteria. Additionally, they are a good source of complex carbohydrates, providing sustained energy, which is particularly beneficial for athletes and those requiring long-lasting energy throughout the day. Potatoes are also naturally gluten-free, making them a great dietary choice for individuals with gluten sensitivities or celiac disease.",
    heading3:"Nutritional Value of Potatoes",
    para3a:"Nutritionally, potatoes are more than just a source of carbs. A medium-sized potato (about 150 grams) contains around 110 calories, primarily from carbohydrates, but it also offers a wealth of vitamins and minerals. Potatoes are rich in vitamin C, an essential nutrient for immune health and skin vitality, with one potato providing nearly 30% of the recommended daily intake. They are also a good source of vitamin B6, which plays a key role in brain function and the production of neurotransmitters. Furthermore, potatoes provide dietary fiber, particularly when eaten with the skin, which aids in digestion and helps maintain healthy blood sugar levels. They also contain small amounts of iron, magnesium, and phosphorus, all of which contribute to overall metabolic health.",
    para3b:"Potatoes are a versatile, nutrient-dense food that offers numerous health benefits. Whether baked, mashed, or roasted, they can be incorporated into a balanced diet to provide energy, support heart health, and promote digestion. Their affordability and adaptability make them a valuable food in kitchens around the world.",
   },
   {
    id:23,
    title: "Onion",
    description: "Onions (Allium cepa) are one of the most widely used vegetables in global cuisine, valued for their distinct flavor and...",
    image: onion_veg,
    date: Date.now(),
    category: 'Vegetables',
    heading1:"Onion: An Overview",
    para1a:"Onions (Allium cepa) are one of the most widely used vegetables in global cuisine, valued for their distinct flavor and versatility. Native to Central Asia, onions have been cultivated for thousands of years and are a staple ingredient in kitchens worldwide. They come in various types, including red, yellow, white, and green onions, each offering a slightly different flavor profile, from sweet to pungent. Onions can be consumed raw, sautéed, caramelized, roasted, or added to soups, stews, and salads. Their ability to enhance the flavor of dishes, along with their rich history in cooking and traditional medicine, makes onions an indispensable part of many cuisines.",
    heading2:"Benefits of Onion",
    para2a:"Onions are packed with health benefits, primarily due to their high content of antioxidants and sulfur-containing compounds. One of the most notable antioxidants in onions is quercetin, which has been shown to have anti-inflammatory, anti-cancer, and heart-protective properties. Regular consumption of onions may help improve heart health by lowering blood pressure, reducing cholesterol levels, and preventing blood clots. Onions also have antimicrobial properties that can help fight infections, and they are traditionally used to soothe cold and flu symptoms. Additionally, onions are known to promote digestive health due to their high content of prebiotic fibers, which support the growth of beneficial gut bacteria.",
    heading3:"Nutritional Value of Onion",
    para3a:"Nutritionally, onions are low in calories but rich in essential vitamins and minerals. A 100-gram serving of raw onion contains approximately 40 calories, making them an excellent low-calorie addition to meals. Onions are a good source of vitamin C, which supports immune function and skin health. They also provide small amounts of vitamin B6 and folate, which are important for energy metabolism and red blood cell production. Onions contain important minerals such as potassium, which helps regulate blood pressure, and manganese, which plays a role in bone health and metabolic processes. Additionally, the sulfur compounds in onions, such as allicin, contribute to their medicinal properties and give them their characteristic pungent flavor.",
    para3b:"Onions are not only a flavorful and versatile ingredient but also a powerhouse of health benefits. Their rich antioxidant content, along with their ability to promote heart and gut health, makes them an excellent addition to a balanced diet. Whether enjoyed raw or cooked, onions continue to be a staple in both culinary and medicinal practices around the world.",
   },
   {
    id:24,
    title: "Garlic",
    description: "Garlic (Allium sativum) is a widely used culinary herb that has been cherished for its flavor and medicinal properties for...",
    image: garlic_veg,
    date: Date.now(),
    category: 'Vegetables',
    heading1:"Garlic: An Overview",
    para1a:"Garlic (Allium sativum) is a widely used culinary herb that has been cherished for its flavor and medicinal properties for thousands of years. Native to Central Asia, garlic is part of the allium family, which includes onions, leeks, and shallots. Its strong, pungent aroma and unique taste make it a staple ingredient in many cuisines around the world, from Mediterranean to Asian dishes. Garlic is typically used fresh, minced, roasted, or powdered, and can be found in a variety of recipes, from sauces to marinades and soups. Its rich history extends beyond the kitchen, as garlic has also been valued in traditional medicine for its therapeutic benefits.",
    heading2:"Benefits of Garlic",
    para2a:"Garlic is celebrated for its numerous health benefits, largely attributed to its sulfur-containing compounds, particularly allicin. Allicin, which is released when garlic is chopped or crushed, has powerful antioxidant, antimicrobial, and anti-inflammatory properties. Regular consumption of garlic is known to support heart health by reducing cholesterol levels, lowering blood pressure, and improving blood circulation. Garlic may also enhance immune function, helping the body ward off infections and viruses. Studies suggest that garlic's compounds can even help reduce the risk of certain cancers by inhibiting the growth of cancer cells. Additionally, garlic has been used traditionally to help with conditions such as colds, coughs, and digestive issues.",
    heading3:"Nutritional Value of Garlic",
    para3a:"Nutritionally, garlic is low in calories but packed with important vitamins and minerals. A 100-gram serving of garlic provides around 149 calories, but it’s typically consumed in much smaller quantities due to its potent flavor. Garlic is a good source of vitamin C, vitamin B6, and manganese. Vitamin C acts as an antioxidant, supporting immune health and skin integrity, while vitamin B6 is important for brain function and metabolism. Manganese, which is abundant in garlic, plays a key role in bone health and metabolic processes. Garlic also contains trace amounts of other nutrients like selenium, calcium, and iron, further contributing to its nutritional value.",
    para3b:"garlic is not only a culinary powerhouse but also a natural remedy with a wide range of health benefits. Its ability to improve heart health, boost immunity, and provide essential nutrients makes it a valuable addition to a healthy diet. Whether used to enhance the flavor of a dish or as a natural supplement, garlic continues to be a beloved ingredient in both cooking and traditional medicine.",
   },
   {
    id:25,
    title: "Ginger",
    description: "Ginger, scientifically known as Zingiber officinale, is a flowering plant whose rhizome, commonly referred to as ginger root, is...",
    image: ginger_veg,
    date: Date.now(),
    category: 'Vegetables',
    heading1:"Ginger: An Overview",
    para1a:"Ginger, scientifically known as Zingiber officinale, is a flowering plant whose rhizome, commonly referred to as ginger root, is widely used as a spice and a traditional medicine. Originating in Southeast Asia, ginger has been cherished for its distinctive spicy flavor and numerous health benefits for thousands of years. Its signature taste and aroma come from natural oils, particularly gingerol, a compound known for its powerful anti-inflammatory and antioxidant properties.",
    para1b:"Over time, ginger has become a staple in culinary and medicinal practices around the globe. It is versatile, available in fresh, dried, powdered, oil, or juice forms, and can be incorporated into a wide array of dishes and remedies. Its historical significance and ongoing popularity make it a timeless ingredient valued in kitchens and medicine cabinets alike",
    heading2:"Benefits of Ginger",
    para2a:"Boosts Immunity:Ginger’s antimicrobial and anti-inflammatory properties strengthen the immune system. It’s particularly beneficial during cold and flu seasons, helping to alleviate symptoms such as congestion and sore throat. A warm cup of ginger tea with honey is a popular home remedy to fend off common illnesses",
    para2b:"Supports Digestive Health:Ginger is widely recognized for its ability to ease digestion and combat nausea. Its active compounds aid in breaking down food and promoting smoother digestion. It’s especially effective for reducing nausea caused by morning sickness, motion sickness, and chemotherapy. Sipping on ginger tea or chewing ginger candy provides quick relief for an upset stomach.",
    heading3:"Nutritional Value of Garlic",
    para3a:"Ginger is not just a culinary delight but a nutritional powerhouse packed with essential nutrients and bioactive compounds. It contains a modest number of calories, making it a great addition to any diet without contributing to weight gain. Per 100 grams, ginger provides approximately 80 calories, 18 grams of carbohydrates, and 2 grams of fiber, supporting energy needs and digestive health. It is also a source of protein and healthy fats, albeit in smaller amounts. Rich in potassium and magnesium, ginger helps regulate blood pressure and maintain nerve and muscle function. Furthermore, its vitamin C content contributes to immune support, while vitamin B6 plays a role in brain development and function.",
    para3b:"In addition to its macronutrients, ginger is abundant in antioxidants, including gingerol, shogaol, and paradol, which combat oxidative stress and inflammation. These compounds have been linked to reducing the risk of chronic diseases such as heart disease and certain cancers. Ginger also contains trace amounts of essential minerals like zinc, iron, and phosphorus, which collectively support overall health and well-being. Its nutrient profile, combined with its unique bioactive properties, underscores its role as both a functional food and a therapeutic remedy.",
   }
   

]

export default product_data